name: 'Smart PR Description Reviewer'
description: 'AI-powered tool to review and validate pull request descriptions'
author: 'BizCloud Experts'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for reviewing descriptions'
    required: true
  min-score:
    description: 'Minimum score required to pass review (0-100)'
    required: false
    default: '80'

runs:
  using: 'node16'
  main: 'src/index.js'

branding:
  icon: 'edit-3'
  color: 'blue'